### ISSUE TITLE
Cannot build included content

### ISSUE THREAD

**Issue by invisnet** [getstattic/stattic#10]
Immediately after `git clone`:

```
$ python3 stattic.py --site-url example.com
...
ERROR - Failed to generate post say-hello-to-stattic: strptime() argument 1 must be str, not datetime.date
Traceback (most recent call last):
  File "stattic.py", line 972, in <module>
    generator.build()
  File "stattic.py", line 926, in build
    self.build_posts_and_pages()
  File "stattic.py", line 626, in build_posts_and_pages
    self.build_post_or_page(metadata, html_content, post_slug, post_output_dir, is_page=False)
  File "stattic.py", line 523, in build_post_or_page
    formatted_date = self.format_date(metadata.get('date'))
  File "stattic.py", line 151, in format_date
    date_obj = datetime.strptime(date_str, '%Y-%m-%dT%H:%M:%S')
TypeError: strptime() argument 1 must be str, not datetime.date
```

**Comment by robertdevore** [comment]
@invisnet can you pull from the main branch and try again? I just pushed updates that included some fixes for the datetime issue.

**Comment by invisnet** [comment]
That's got it.

The only thing of note in the log now is:
```
WARNING - Skipping non-image URL: /
```
which I assume is harmless (and unrelated).
